<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>IconoCalculadora.ico</ApplicationIcon>
    <Authors>Jim</Authors>
    <Product>Calculadora</Product>
    <Copyright>no-copiar</Copyright>
    <AssemblyVersion>1.0</AssemblyVersion>
    <FileVersion>1.0</FileVersion>
    <PackageIcon>IconoCalculadora.ico</PackageIcon>
    <NeutralLanguage>es</NeutralLanguage>
    <Description>Es una calculador en desarrollo</Description>
    <PackageId>Calculadora</PackageId>
    <Title>Calculadora</Title>
    <RepositoryUrl>https://github.com/pandrio133/Calculadora.git</RepositoryUrl>
    <PackAsTool>True</PackAsTool>
    <ToolCommandName>Calculadora</ToolCommandName>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="IconoCalculadora.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="IconoCalculadora.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
